// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTask.Repositories;

#nullable disable

namespace TestTask.Api.Migrations
{
    [DbContext(typeof(StoreEntities))]
    partial class StoreEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestTask.Domain.Entities.AccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.CountryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Австралия"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Австрия"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Азербайджан"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Албания"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Алжир"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ангола"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Андорра"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Антигуа и Барбуда"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Аргентина"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Армения"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Афганистан"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Багамы"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Бангладеш"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Барбадос"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Бахрейн"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Белиз"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Белоруссия"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Бельгия"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Бенин"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Болгария"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Боливия"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Босния и Герцеговина"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Ботсвана"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Бразилия"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Бруней"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Буркина-Фасо"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Бурунди"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Бутан"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Вануату"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Ватикан"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Великобритания"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Венгрия"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Венесуэла"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Восточный Тимор"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Вьетнам"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Габон"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Гаити"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Гайана"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Гамбия"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Гана"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Гватемала"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Гвинея"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Гвинея-Бисау"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Германия"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Гондурас"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Гренада"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Греция"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Грузия"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Дания"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Джибути"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Доминика"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Доминиканская Республика"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Египет"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Замбия"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Зимбабве"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Израиль"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Индия"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Индонезия"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Иордания"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Ирак"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Иран"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Ирландия"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Исландия"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Испания"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Италия"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Йемен"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Кабо-Верде"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Казахстан"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Камбоджа"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Камерун"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Канада"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Катар"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Кения"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Кипр"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Киргизия"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Кирибати"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Китай"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Колумбия"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Коморы"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Конго"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Конго, Демократическая Республика"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Коста-Рика"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Кот-д'Ивуар"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Куба"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Кувейт"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Лаос"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Латвия"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Лесото"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Либерия"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Ливан"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Ливия"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Литва"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Лихтенштейн"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Люксембург"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Маврикий"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Мавритания"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Мадагаскар"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Малави"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Малайзия"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Мали"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Мальдивы"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Мальта"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Марокко"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Маршалловы Острова"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Мексика"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Микронезия"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Мозамбик"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Молдова"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Монако"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Монголия"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Мьянма"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Намибия"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Науру"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Непал"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Нигер"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Нигерия"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Нидерланды"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Никарагуа"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Новая Зеландия"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Норвегия"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Объединенные Арабские Эмираты"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Оман"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Пакистан"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Палау"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Панама"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Папуа — Новая Гвинея"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Парагвай"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Перу"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Польша"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Португалия"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Россия"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Руанда"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Румыния"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Сальвадор"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Самоа"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Сан-Марино"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Саудовская Аравия"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Северная Македония"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Сейшелы"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Сенегал"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Сент-Винсент и Гренадины"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Сент-Китс и Невис"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Сент-Люсия"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Сербия"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Сингапур"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Сирия"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Словакия"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Словения"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Соломоновы Острова"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Сомали"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Судан"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Суринам"
                        },
                        new
                        {
                            Id = 153,
                            Name = "США"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Сьерра-Леоне"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Таджикистан"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Таиланд"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Танзания"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Того"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Тонга"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Тринидад и Тобаго"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Тувалу"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Тунис"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Туркмения"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Турция"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Уганда"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Узбекистан"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Украина"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Уругвай"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Фиджи"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Филиппины"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Финляндия"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Франция"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Хорватия"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Центральноафриканская Республика"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Чад"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Черногория"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Чехия"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Чили"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Швейцария"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Швеция"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Шри-Ланка"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Эквадор"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Экваториальная Гвинея"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Эритрея"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Эсватини"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Эстония"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Эфиопия"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Южная Корея"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Южно-Африканская Республика"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Южный Судан"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Ямайка"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Япония"
                        });
                });

            modelBuilder.Entity("TestTask.Domain.Entities.ProvinceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Новый Южный Уэльс"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Виктория"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Квинсленд"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Вена"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 2,
                            Name = "Штирия"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            Name = "Тироль"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 3,
                            Name = "Баку"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 3,
                            Name = "Гянджа"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 3,
                            Name = "Сумгаит"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 4,
                            Name = "Тирана"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 4,
                            Name = "Дуррес"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 4,
                            Name = "Влёра"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 5,
                            Name = "Алжир"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 5,
                            Name = "Оран"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 5,
                            Name = "Константина"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 6,
                            Name = "Луанда"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 6,
                            Name = "Бенгела"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 6,
                            Name = "Лубанго"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 7,
                            Name = "Андорра-ла-Велья"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 7,
                            Name = "Эскальдес"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 8,
                            Name = "Сент-Джонс"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 8,
                            Name = "Поттерс"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 9,
                            Name = "Буэнос-Айрес"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 9,
                            Name = "Кордова"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 9,
                            Name = "Мендоса"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 10,
                            Name = "Ереван"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 10,
                            Name = "Гюмри"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 10,
                            Name = "Ванадзор"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 11,
                            Name = "Кабул"
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 11,
                            Name = "Кандагар"
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 11,
                            Name = "Герат"
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 12,
                            Name = "Нассау"
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 12,
                            Name = "Фрипорт"
                        },
                        new
                        {
                            Id = 34,
                            CountryId = 12,
                            Name = "Марафон"
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 13,
                            Name = "Дакка"
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 13,
                            Name = "Читтагонг"
                        },
                        new
                        {
                            Id = 37,
                            CountryId = 13,
                            Name = "Кхулна"
                        },
                        new
                        {
                            Id = 38,
                            CountryId = 14,
                            Name = "Бриджтаун"
                        },
                        new
                        {
                            Id = 39,
                            CountryId = 15,
                            Name = "Манама"
                        },
                        new
                        {
                            Id = 40,
                            CountryId = 15,
                            Name = "Риффа"
                        },
                        new
                        {
                            Id = 41,
                            CountryId = 16,
                            Name = "Бельмопан"
                        },
                        new
                        {
                            Id = 42,
                            CountryId = 16,
                            Name = "Сан-Игнасио"
                        },
                        new
                        {
                            Id = 43,
                            CountryId = 17,
                            Name = "Минск"
                        },
                        new
                        {
                            Id = 44,
                            CountryId = 17,
                            Name = "Гомель"
                        },
                        new
                        {
                            Id = 45,
                            CountryId = 18,
                            Name = "Брюссель"
                        },
                        new
                        {
                            Id = 46,
                            CountryId = 18,
                            Name = "Антверпен"
                        },
                        new
                        {
                            Id = 47,
                            CountryId = 18,
                            Name = "Гент"
                        },
                        new
                        {
                            Id = 48,
                            CountryId = 19,
                            Name = "Порто-Ново"
                        },
                        new
                        {
                            Id = 49,
                            CountryId = 19,
                            Name = "Котону"
                        },
                        new
                        {
                            Id = 50,
                            CountryId = 20,
                            Name = "София"
                        },
                        new
                        {
                            Id = 51,
                            CountryId = 20,
                            Name = "Пловдив"
                        },
                        new
                        {
                            Id = 52,
                            CountryId = 20,
                            Name = "Варна"
                        });
                });

            modelBuilder.Entity("TestTask.Domain.Entities.AccountEntity", b =>
                {
                    b.HasOne("TestTask.Domain.Entities.CountryEntity", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestTask.Domain.Entities.ProvinceEntity", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.ProvinceEntity", b =>
                {
                    b.HasOne("TestTask.Domain.Entities.CountryEntity", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TestTask.Domain.Entities.CountryEntity", b =>
                {
                    b.Navigation("Provinces");
                });
#pragma warning restore 612, 618
        }
    }
}
